version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  AfterInstall:
  - location: scripts/install_dependencies.sh
    timeout: 300
  - location: script/AfterInstall.sh